ETHIOPIA_GRAPH = {
    'Gambella': ['Dembi Dollo', 'Gore'],
    'Dembi Dollo': ['Gambella', 'Gimbi'],
    'Gimbi': ['Dembi Dollo', 'Nekemete'],
    'Nekemete': ['Gimbi', 'Ambo', 'Bedelle'],
    'Gore': ['Gambella', 'Tepi', 'Bedelle'],
    'Tepi': ['Gore', 'Bonga', 'Mezan Teferi'],
    'Mezan Teferi': ['Tepi', 'Bonga'],
    'Bonga': ['Tepi', 'Mezan Teferi', 'Dawro', 'Jimma'],
    'Jimma': ['Bonga', 'Bedelle', 'Wolkite'],
    'Bedelle': ['Nekemete', 'Gore', 'Jimma'],
    'Dawro': ['Bonga', 'Wolaita Sodo'],
    'Wolaita Sodo': ['Dawro', 'Arba Minch', 'Hossana'],
    'Arba Minch': ['Wolaita Sodo'],
    'Wolkite': ['Jimma', 'Ambo', 'Worabe', 'Hossana'],
    'Worabe': ['Wolkite', 'Buta Jirra', 'Hossana'],
    'Hossana': ['Wolkite', 'Worabe', 'Wolaita Sodo', 'Shashemene'],
    'Buta Jirra': ['Worabe', 'Batu'],
    'Ambo': ['Nekemete', 'Addis Ababa', 'Wolkite'],
    'Addis Ababa': ['Ambo', 'Debre Birhan', 'Adama'],
    'Debre Birhan': ['Addis Ababa'],
    'Adama': ['Addis Ababa', 'Matahara', 'Batu', 'Assella'],
    'Matahara': ['Adama', 'Awash'],
    'Awash': ['Matahara', 'Chiro'],
    'Chiro': ['Awash', 'Dire Dawa'],
    'Dire Dawa': ['Chiro', 'Harar'],
    'Harar': ['Dire Dawa', 'Babile'],
    'Babile': ['Harar', 'Jigjiga'],
    'Jigjiga': ['Babile', 'Dega Habur'],
    'Dega Habur': ['Jigjiga', 'Kebri Dehar', 'Goba'],
    'Kebri Dehar': ['Dega Habur', 'Gode', 'Sof Oumer'],
    'Gode': ['Kebri Dehar'],
    'Batu': ['Buta Jirra', 'Adama', 'Shashemene'],
    'Shashemene': ['Batu', 'Hossana', 'Hawassa', 'Dodolla'],
    'Hawassa': ['Shashemene', 'Dilla'],
    'Dilla': ['Hawassa'],
    'Assella': ['Adama', 'Assasa'],
    'Assasa': ['Assella', 'Dodolla'],
    'Dodolla': ['Assasa', 'Shashemene', 'Bale'],
    'Bale': ['Dodolla', 'Goba', 'Sof Oumer'],
    'Goba': ['Bale', 'Dega Habur'],
    'Sof Oumer': ['Bale', 'Kebri Dehar']
}

